export const ADD_COMMENT = 'ADD_COMMENT';
export const DISHES_LOADING = 'DISHES_LOADING'; // ACTION OF DISHES BEING FETCHED FROM SERVER 
export const DISHES_FAILED = 'DISHES_FAILED';// ACTION OF DISHES FETCHING FAILED
export const ADD_DISHES = 'ADD_DISHES'; // ADD DISHES TO STORE
